package gatewayapihttproute

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"testing"

	k8gbv1beta1 "github.com/k8gb-io/k8gb/api/v1beta1"
	"github.com/k8gb-io/k8gb/controllers/utils"
	"github.com/stretchr/testify/assert"
)

func TestGetServers(t *testing.T) {
	var tests = []struct {
		name            string
		httpRouteFile   string
		expectedServers []*k8gbv1beta1.Server
	}{
		{
			name:          "single hostname and backend, without backend namespace",
			httpRouteFile: "../testdata/gatewayapi_httproute.yaml",
			expectedServers: []*k8gbv1beta1.Server{
				{
					Hostname: "gatewayapi-httproute.cloud.example.com",
					Services: []*k8gbv1beta1.NamespacedName{
						{
							Name:      "gatewayapi-service",
							Namespace: "test-gslb",
						},
					},
				},
			},
		},
		{
			name:          "single hostname and backend, backend with namespace specified",
			httpRouteFile: "./testdata/gatewayapi_httproute_backend_with_namespace.yaml",
			expectedServers: []*k8gbv1beta1.Server{
				{
					Hostname: "gatewayapi-httproute.cloud.example.com",
					Services: []*k8gbv1beta1.NamespacedName{
						{
							Name:      "gatewayapi-service",
							Namespace: "test-backend",
						},
					},
				},
			},
		},
		{
			name:          "multiple hostnames",
			httpRouteFile: "./testdata/gatewayapi_httproute_multiple_hostnames.yaml",
			expectedServers: []*k8gbv1beta1.Server{
				{
					Hostname: "gatewayapi-httproute1.cloud.example.com",
					Services: []*k8gbv1beta1.NamespacedName{
						{
							Name:      "gatewayapi-service",
							Namespace: "test-gslb",
						},
					},
				},
				{
					Hostname: "gatewayapi-httproute2.cloud.example.com",
					Services: []*k8gbv1beta1.NamespacedName{
						{
							Name:      "gatewayapi-service",
							Namespace: "test-gslb",
						},
					},
				},
			},
		},
		{
			name:          "multiple backendRefs",
			httpRouteFile: "./testdata/gatewayapi_httproute_multiple_backendrefs.yaml",
			expectedServers: []*k8gbv1beta1.Server{
				{
					Hostname: "gatewayapi-httproute.cloud.example.com",
					Services: []*k8gbv1beta1.NamespacedName{
						{
							Name:      "gatewayapi-service1",
							Namespace: "test-gslb",
						},
						{
							Name:      "gatewayapi-service2",
							Namespace: "test-gslb",
						},
					},
				},
			},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			// arrange
			httpRoute := utils.FileToGatewayAPIHTTPRoute(test.httpRouteFile)
			resolver := ReferenceResolver{
				httpRoute: httpRoute,
			}

			// act
			servers, err := resolver.GetServers()
			assert.NoError(t, err)

			// assert
			assert.Equal(t, test.expectedServers, servers)
		})
	}
}

func TestGetGslbExposedIPs(t *testing.T) {
	var tests = []struct {
		name          string
		annotations   map[string]string
		gatewayYaml   string
		expectedIPs   []string
		expectedError bool
	}{
		{
			name:          "no exposed IPs",
			gatewayYaml:   "./testdata/gatewayapi_gateway_no_ips.yaml",
			annotations:   map[string]string{},
			expectedIPs:   []string{},
			expectedError: false,
		},
		{
			name:          "single exposed IP",
			annotations:   map[string]string{},
			gatewayYaml:   "../testdata/gatewayapi_gateway.yaml",
			expectedIPs:   []string{"10.0.0.1"},
			expectedError: false,
		},
		{
			name:          "multiple exposed IPs",
			annotations:   map[string]string{},
			gatewayYaml:   "./testdata/gatewayapi_gateway_multiple_ips.yaml",
			expectedIPs:   []string{"10.0.0.1", "10.0.0.2"},
			expectedError: false,
		},
		{
			name:          "annotation with no exposed IPs",
			annotations:   map[string]string{"k8gb.io/exposed-ip-addresses": ""},
			gatewayYaml:   "./testdata/gatewayapi_gateway_multiple_ips.yaml",
			expectedIPs:   []string{},
			expectedError: true,
		},
		{
			name:          "annotation with single exposed IP",
			annotations:   map[string]string{"k8gb.io/exposed-ip-addresses": "185.199.110.153"},
			gatewayYaml:   "./testdata/gatewayapi_gateway_multiple_ips.yaml",
			expectedIPs:   []string{"185.199.110.153"},
			expectedError: false,
		},
		{
			name:          "annotation with invalid IP",
			annotations:   map[string]string{"k8gb.io/exposed-ip-addresses": "192.169.0.test"},
			gatewayYaml:   "./testdata/gatewayapi_gateway_multiple_ips.yaml",
			expectedIPs:   []string{},
			expectedError: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// arrange
			gateway := utils.FileToGatewayAPIGateway(tt.gatewayYaml)
			resolver := ReferenceResolver{
				gateway: gateway,
			}

			// act
			IPs, err := resolver.GetGslbExposedIPs(tt.annotations, []utils.DNSServer{})
			if tt.expectedError {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}

			// assert
			assert.Equal(t, tt.expectedIPs, IPs)
		})
	}
}
