# Copyright 2021 The k8gb Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic

JEKYLL_VERSION = 4.2.0
PWD ?=  $(shell pwd)
JEKYLL_PORT ?= 4000
JEKYLL_HOST ?= 0.0.0.0

# Bootstrap env vars from "dotenv" file
ifneq ($(wildcard ./.env),)
	include .env
	export
endif

# Detect custom certificate
ifneq ($(CUSTOM_CERT_PATH),)
	CUSTOM_CERT_PATH := $(abspath $(CUSTOM_CERT_PATH))
	CERT_INSTALL_CMD := update-ca-certificates;
endif

JEKYLL_CMD := "$(CERT_INSTALL_CMD) bundle install; jekyll serve --host $(JEKYLL_HOST) --watch --livereload --incremental --port $(JEKYLL_PORT)"

# Build and serve k8gb.io website locally with watch and livereload
.PHONY: serve
serve:
ifneq ($(CUSTOM_CERT_PATH),)
	@echo "Using custom certificate: $(CUSTOM_CERT_PATH)"
endif
	@echo "Building and serving k8gb.io website at http://$(JEKYLL_HOST):$(JEKYLL_PORT) ⌛ ..."
ifneq ($(JEKYLL_GITHUB_TOKEN),)
	@docker run --rm -it \
		--env JEKYLL_GITHUB_TOKEN=$(JEKYLL_GITHUB_TOKEN) \
		--volume="$(PWD):/srv/jekyll" \
		--volume="$(PWD)/vendor/bundle:/usr/local/bundle" \
		--volume="$(CUSTOM_CERT_PATH):/usr/local/share/ca-certificates/custom-cert" \
		-p $(JEKYLL_PORT):$(JEKYLL_PORT) -p 35729:35729 jekyll/jekyll:$(JEKYLL_VERSION) \
 		sh -c $(JEKYLL_CMD)
else
	@echo "GitHub pages are using the GitHub API to obtain repository metadata for the website generation."
	@echo "Local generation requires a GitHub PAT token with the 'public_repo' scope (https://github.com/settings/tokens/new)."
	@echo "The token should be assigned to the JEKYLL_GITHUB_TOKEN environment variable."
endif
