# https://taskfile.dev/usage/
# use this to get: k8gb.edgeDNSServers[0]
# docker network inspect k3d-action-bridge-network -f '{{ (index .IPAM.Config 0).Gateway }}'
version: '3'
env:
  VERSION: "v0.15.12-rc2-amd64"
  MAKE_VERSION: "v0.14.0"
  MAKE_COMMIT_HASH: "d8db536f"
  MAKE_ARCH: "amd64"
  HELM_PACKAGE: k8gb
  CHART: ./charts

dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

tasks:

  version:
    cmds:
      - echo $VERSION

  start-*:
    vars:
      CLUSTER: '{{index .MATCH 0}}'
    cmds:
      - echo "starting {{.CLUSTER}}"
      - kubectl -n k8gb scale deployment k8gb --replicas=1 --context={{.CLUSTER}}
    description: "k3d-test-gslb2 = us, k3d-test-gslb1 = eu"

  stop-*:
    vars:
      CLUSTER: '{{index .MATCH 0}}'
    cmds:
      - echo stopping {{.CLUSTER}}
      - kubectl -n k8gb scale deployment k8gb --replicas=0 --context={{.CLUSTER}}
    description: "k3d-test-gslb2 = us, k3d-test-gslb1 = eu"
    ignore_error: true

  install-makefile:
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w -X main.version=$VERSION -X main.commit=123" -o ./k8gb main.go
      - docker build . -t docker.io/absaoss/k8gb:$MAKE_VERSION-$MAKE_COMMIT_HASH-$MAKE_ARCH
      - VERSION=$MAKE_VERSION COMMIT_HASH=$MAKE_COMMIT_HASH ARCH=$MAKE_ARCH make deploy-test-version

  install:
    cmds:
      - defer: { task: us}
      - echo "Installing current k8gb $VERSION"
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w -X main.version=$VERSION -X main.commit=123" -o ./k8gb main.go
      - docker build . -t docker.io/kuritka/k8gb:$VERSION
      - k3d image import docker.io/kuritka/k8gb:$VERSION -c test-gslb1
      - k3d image import docker.io/kuritka/k8gb:$VERSION -c test-gslb2
      - task: stop
      - task: clean
      - kubectl create namespace k8gb --dry-run=client -o yaml | kubectl apply -f - --context=k3d-test-gslb1
      - kubectl create namespace k8gb --dry-run=client -o yaml | kubectl apply -f - --context=k3d-test-gslb2
      - kubectl apply -f ./deploy/crds/init-ingress.yaml --context=k3d-test-gslb1
      - kubectl apply -f ./deploy/crds/init-ingress.yaml --context=k3d-test-gslb2
      - kubectl -n k8gb create secret generic rfc2136 --from-literal=secret=96Ah/a2g0/nLeFGK+d/0tzQcccf9hCEIy34PoXX2Qg8= || true
      - task: install-helm
    #      - task: stop-us
    silent: true

  stop:
    cmds:
      - task: stop-k3d-test-gslb1
      - task: stop-k3d-test-gslb2

  stop-us:
    cmds:
      - task: stop-k3d-test-gslb2

  stop-eu:
    cmds:
      - task: stop-k3d-test-gslb1

  start-us:
    cmds:
      - task: start-k3d-test-gslb2

  start-eu:
    cmds:
      - task: start-k3d-test-gslb1

  us:
    cmds:
      - kubectl config use-context k3d-test-gslb2
  eu:
    cmds:
      - kubectl config use-context k3d-test-gslb1

  install-helm:
    cmds:
      - task: stop
      - task: us
      - helm -n k8gb upgrade -i k8gb ./chart/k8gb -f ./chart/k8gb/values.yaml
        --set k8gb.imageRepo=docker.io/kuritka/k8gb
        --set k8gb.clusterGeoTag=us
        --set k8gb.extGslbClustersGeoTags=eu
        --set k8gb.reconcileRequeueSeconds=10
        --set k8gb.imageTag=$VERSION
        --set k8gb.log.format=simple
        --set k8gb.log.level=debug
        --set rfc2136.enabled=true
        --set k8gb.edgeDNSServers[0]=172.18.0.1:1053
        --set k8gb.dnsZones[0].zone="example.com"
        --set k8gb.dnsZones[0].domain="cloud.example.com"
        --set k8gb.dnsZones[0].dnsZoneNegTTL=30
        --wait --timeout=10m0s
      - task: eu
      - helm -n k8gb upgrade -i k8gb ./chart/k8gb -f ./chart/k8gb/values.yaml
        --set k8gb.imageRepo=docker.io/kuritka/k8gb
        --set k8gb.clusterGeoTag=eu
        --set k8gb.extGslbClustersGeoTags=us
        --set k8gb.reconcileRequeueSeconds=10
        --set k8gb.imageTag=$VERSION
        --set k8gb.log.format=simple
        --set k8gb.log.level=debug
        --set rfc2136.enabled=true
        --set k8gb.edgeDNSServers[0]=172.18.0.1:1053
        --set k8gb.dnsZones[0].zone="example.com"
        --set k8gb.dnsZones[0].domain="cloud.example.com"
        --set k8gb.dnsZones[0].dnsZoneNegTTL=30
        --wait --timeout=10m0s

  clean-*:
    vars:
      CLUSTER: '{{index .MATCH 0}}'
    cmds:
      - echo cleaning {{.CLUSTER}}
      - kubectl delete ns -l k8gb.io/terratest=true --context={{.CLUSTER}}
      - kubectl delete dnsendpoint --all -n k8gb --context={{.CLUSTER}}
    description: "clean unused namespaces and default dnsendpoint"

  clean-eu:
    silent: true
    cmds:
      - task: clean-k3d-test-gslb1

  clean-us:
    silent: true
    cmds:
      - task: clean-k3d-test-gslb2

  clean:
    silent: true
    cmds:
      - task: clean-eu
      - task: clean-us

  publish-amd64:
    cmds:
      - echo "Building k8gb-$VERSION"
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w -X main.version=$VERSION -X main.commit=123" -o ./k8gb main.go
      - docker buildx build --platform linux/amd64 -t docker.io/kuritka/k8gb:$VERSION .
      - docker push docker.io/kuritka/k8gb:$VERSION

  retag:
    cmds:
      - docker pull --platform=linux/amd64 artifacts.bcp.absa.co.za/docker.io/kuritka/k8gb:$VERSION
      - docker tag artifacts.bcp.absa.co.za/docker.io/kuritka/k8gb:$VERSION artifacts.bcp.absa.co.za/bks-docker-local/k8gb/k8gb:$VERSION
      - docker push artifacts.bcp.absa.co.za/bks-docker-local/k8gb/k8gb:$VERSION

  # change versions in Charts.yaml
  # requires .env file
  # ARTIFACTORY_USER=
  # ARTIFACTORY_PASSWORD=
  helm:
    cmds:
      - task: retag
      - cd ./chart && helm package $HELM_PACKAGE
      - curl -u $ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD -T ./chart/$HELM_PACKAGE-$VERSION.tgz "https://artifacts.bcp.absa.co.za/artifactory/bks-helm-local/$HELM_PACKAGE-$VERSION.tgz"
      - curl -u $ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD -X POST "https://artifacts.bcp.absa.co.za/artifactory/bks-helm-local/$HELM_PACKAGE/"
      - curl -u $ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD  "https://artifacts.bcp.absa.co.za/artifactory/bks-helm-local/index.yaml" --output ./index.yaml --silent
      - sed -i -e 's/artifacts.cto-bcp.sdc-prod.caas.absa.co.za/artifacts.bcp.absa.co.za/g' index.yaml
      - curl -u $ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD -X DELETE "https://artifacts.bcp.absa.co.za/artifactory/bks-helm-local/index.yaml"
      - curl -u $ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD -T index.yaml "https://artifacts.bcp.absa.co.za/artifactory/bks-helm-local/index.yaml"
      - rm -f index.yaml index.yaml-e out.yaml
      - echo "image artifacts.bcp.absa.co.za/bks-docker-local/k8gb/k8gb:$VERSION"
      - echo "helm https://artifacts.bcp.absa.co.za/artifactory/bks-helm-local/$HELM_PACKAGE/$HELM_PACKAGE-$VERSION.tgz"
