package refresolver

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import "github.com/k8gb-io/k8gb/controllers/utils"

// ResolveGslbExposedIPs returns the application target IPs (localtargets-*/final A
// records) for a Gslb, honoring the cluster-level EDGE_DNS_EXPOSED_IPS override.
//
// Precedence, from highest to lowest:
//  1. Per-Gslb override annotations (k8gb.io/exposed-hostnames, k8gb.io/exposed-ip-addresses)
//  2. Cluster-level EDGE_DNS_EXPOSED_IPS override
//  3. IPs discovered from the Gslb's referenced application resource
//
// The cluster-level override mirrors the NS-glue override applied in ipresolver, so
// bare-metal / colo clusters behind 1:1 static NAT publish the same publicly routable
// IPs on both delegation paths. See https://github.com/k8gb-io/k8gb/issues/2360
func ResolveGslbExposedIPs(refResolver GslbReferenceResolver, annotations map[string]string,
	clusterOverride []string, parentZoneDNSServers utils.DNSList) ([]string, error) {
	if len(clusterOverride) > 0 && !hasExposedIPOverrideAnnotation(annotations) {
		return clusterOverride, nil
	}
	return refResolver.GetGslbExposedIPs(annotations, parentZoneDNSServers)
}

// hasExposedIPOverrideAnnotation reports whether a Gslb carries a per-Gslb override
// annotation that must take precedence over the cluster-level EDGE_DNS_EXPOSED_IPS override.
func hasExposedIPOverrideAnnotation(annotations map[string]string) bool {
	if _, ok := annotations[utils.ExposedHostnamesAnnotation]; ok {
		return true
	}
	_, ok := annotations[utils.ExternalIPsAnnotation]
	return ok
}
