package k8gbendpoint

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"io"
	"strings"
	"testing"

	"github.com/k8gb-io/k8gb/api/k8gb.io/v1beta1"
	k8gbv1beta1io "github.com/k8gb-io/k8gb/api/v1beta1io"
	"github.com/k8gb-io/k8gb/controllers/mocks"
	"github.com/k8gb-io/k8gb/controllers/resolver"
	"github.com/k8gb-io/k8gb/controllers/zones"
	"github.com/rs/zerolog"
	"github.com/stretchr/testify/assert"
	"go.uber.org/mock/gomock"
)

func TestGetLocalTargetsHostRejectsTooLongFirstLabel(t *testing.T) {
	// With the dot prefix the host is split into labels, so the over-long
	// label must live in the host portion: 64 'a's exceed the 63-char limit.
	host := strings.Repeat("a", 64) + ".cloud.example.com"
	expectedErr := `derived localtargets name "localtargets.` +
		strings.Repeat("a", 64) +
		`.cloud.example.com" is invalid: label "` +
		strings.Repeat("a", 64) +
		`" exceeds 63 characters`

	_, err := getLocalTargetsHost(host)

	assert.EqualError(t, err, expectedErr)
}

func TestGetDNSEndpointRejectsInvalidLocalTargetsHost(t *testing.T) {
	logger := zerolog.New(io.Discard).With().Timestamp().Logger()
	metrics := func(*k8gbv1beta1io.Gslb, bool, k8gbv1beta1io.HealthStatus, []string) {}
	host := strings.Repeat("a", 64) + ".cloud.example.com"

	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	cl := mocks.NewMockClient(ctrl)
	qs := mocks.NewMockDNSQueryService(ctrl)
	zs := zones.NewMockZoneDelegation(ctrl)

	zs.EXPECT().List(gomock.Any()).Return(&v1beta1.ZoneDelegationList{
		Items: []v1beta1.ZoneDelegation{
			{
				Spec: v1beta1.ZoneDelegationSpec{
					LoadBalancedZone: "cloud.example.com",
					ParentZone:       "example.com",
				},
			},
		},
	}, nil)

	ep := NewApplicationDNSEndpoint(
		context.TODO(),
		cl,
		&resolver.Config{ClusterGeoTag: "eu"},
		&k8gbv1beta1io.Gslb{
			Spec: k8gbv1beta1io.GslbSpec{
				Strategy: k8gbv1beta1io.Strategy{
					Type: resolver.RoundRobinStrategy,
				},
			},
			Status: k8gbv1beta1io.GslbStatus{
				ServiceHealth: map[string]k8gbv1beta1io.HealthStatus{
					host: k8gbv1beta1io.Healthy,
				},
				LoadBalancer: k8gbv1beta1io.LoadBalancer{
					ExposedIPs: []string{"10.10.0.1"},
				},
			},
		},
		&logger,
		qs,
		zs,
		metrics,
	)

	endpoint, err := ep.GetDNSEndpoint()

	assert.Nil(t, endpoint)
	assert.ErrorContains(t, err, "invalid internal localtargets record")
	assert.ErrorContains(t, err, `exceeds 63 characters`)
}
