package resolver

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/k8gb-io/k8gb/api/v1beta1io"
	"github.com/k8gb-io/k8gb/controllers/utils"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func parseZoneDelegations(config *Config) (*v1beta1io.ZoneDelegationList, error) {

	// parse example.com:cloud.example.com:30;example.io:cloud.example.io:50
	getEnvAsArrayOfPairsOrFallback := func(zones string) ([]v1beta1io.ZoneDelegation, error) {
		items := make([]v1beta1io.ZoneDelegation, 0)
		slice := strings.Split(zones, ";")
		for _, z := range slice {
			touple := strings.Split(z, ":")
			if len(touple) != 3 {
				return items, fmt.Errorf("invalid format of delegation zones: %s", z)
			}
			negTTL, err := strconv.Atoi(strings.Trim(touple[2], " "))
			if err != nil {
				return nil, fmt.Errorf("invalid value of delegation zones: %s", z)
			}
			items = append(items,
				v1beta1io.ZoneDelegation{
					ObjectMeta: metav1.ObjectMeta{
						Name: touple[1],
					},
					Spec: v1beta1io.ZoneDelegationSpec{
						ParentZone:       strings.Trim(touple[0], " "),
						LoadBalancedZone: strings.Trim(touple[1], " "),
						DoFinalize:       false,
						DNSZoneNegTTL:    negTTL,
					},
				})
		}
		return items, nil
	}

	var zdList = &v1beta1io.ZoneDelegationList{Items: []v1beta1io.ZoneDelegation{}}
	zones := strings.TrimSuffix(strings.TrimSuffix(config.DNSZones, ";"), " ")
	if len(zones) == 0 {
		return zdList, nil
	}

	zds, err := getEnvAsArrayOfPairsOrFallback(zones)
	if err != nil {
		return zdList, err
	}

	for _, z := range zds {
		nsName := getNsName(config.ClusterGeoTag, z.Spec.LoadBalancedZone, z.Spec.ParentZone)
		if err := utils.ValidateRFC1035(nsName); err != nil {
			return zdList, err
		}
		zdList.Items = append(zdList.Items, z)
	}
	return zdList, nil
}
