package resolver

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"fmt"
	"sort"
	"strings"

	"github.com/k8gb-io/k8gb/api/v1beta1io"
)

const prefix = "gslb-ns"

// GeoTag e.g: us, us-east-1
type GeoTag struct {
	isLocal bool
	tag     string
}

func NewGeoTag(isLocal bool, tag string) GeoTag {
	return GeoTag{isLocal: isLocal, tag: tag}
}

func (g GeoTag) IsClusterGeoTag() bool {
	return g.isLocal
}

func (g GeoTag) Name() string {
	return g.tag
}

func (g GeoTag) String() string {
	return g.Name()
}

// ClusterNSNames map of ns name and tag e.g:
// ["gslb-ns-eu-cloud.example.com": "eu", "gslb-ns-us-1-cloud.example.com": "us-1"]
type ClusterNSNames map[string]GeoTag

func getNsName(tag, zone, edge string) string {
	d := strings.TrimSuffix(zone, "."+edge)
	domainX := strings.ReplaceAll(d, ".", "-")
	return fmt.Sprintf("%s-%s-%s.%s", prefix, tag, domainX, edge)
}

func nsSuffix(z *v1beta1io.ZoneDelegation) string {
	d := strings.TrimSuffix(z.Spec.LoadBalancedZone, "."+z.Spec.ParentZone)
	domainX := strings.ReplaceAll(d, ".", "-")
	return fmt.Sprintf("-%s.%s", domainX, z.Spec.ParentZone)
}

func ExtractGeoTagFromNSName(z *v1beta1io.ZoneDelegation, glueA string) (string, error) {
	glueA = strings.TrimSuffix(glueA, ".")
	parts := strings.Split(glueA, prefix)
	if len(parts) != 2 {
		return "", fmt.Errorf("invalid glue A: %s", glueA)
	}
	suffix := nsSuffix(z)
	return strings.ReplaceAll(parts[1], suffix, ""), nil
}

// GetClusterNsNames returns ALL cluster geotags (ClusterGeoTag + ExternalGeoTags)
func (c *Config) GetClusterNsNames(zone *v1beta1io.ZoneDelegation) ClusterNSNames {
	clusterNsNames := make(ClusterNSNames)
	ns := getNsName(c.ClusterGeoTag, zone.Spec.LoadBalancedZone, zone.Spec.ParentZone)
	clusterNsNames[ns] = GeoTag{tag: c.ClusterGeoTag, isLocal: true}
	for _, geotag := range c.ExtClustersGeoTagsRaw {
		ns = getNsName(geotag, zone.Spec.LoadBalancedZone, zone.Spec.ParentZone)
		// if ClusterGeoTag is set to US and ExtClusterGeotags is set to [ZA, US, EU].
		if _, found := clusterNsNames[ns]; found {
			continue
		}
		clusterNsNames[ns] = GeoTag{tag: geotag, isLocal: false}
	}
	return clusterNsNames
}

func (ns ClusterNSNames) ExtClusterNsNames() ClusterNSNames {
	m := make(ClusterNSNames)
	for k, v := range ns {
		if !v.IsClusterGeoTag() {
			m[k] = v
		}
	}
	return m
}

func (ns ClusterNSNames) ClusterGeoTag() GeoTag {
	for _, v := range ns {
		if v.IsClusterGeoTag() {
			return v
		}
	}
	panic("missing ClusterGeoTag")
}

// GetNSServerList returns a sorted list of all NS servers for the delegation zone
func (ns ClusterNSNames) GetNSServerList() []string {
	var list []string
	for k := range ns {
		list = append(list, k)
	}
	sort.Strings(list)
	return list
}

func EqualClusterNSNames(a ClusterNSNames, b ClusterNSNames) bool {
	equalTag := func(a, b GeoTag) bool {
		return a.tag == b.tag && a.isLocal == b.isLocal
	}
	if len(a) != len(b) {
		return false
	}
	for ka, va := range a {
		if vb, found := b[ka]; !found || !equalTag(va, vb) {
			return false
		}
	}
	return true
}
