package controllers

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"testing"

	k8gbv1beta1 "github.com/k8gb-io/k8gb/api/v1beta1"
	k8gbv1beta1io "github.com/k8gb-io/k8gb/api/v1beta1io"
	"github.com/stretchr/testify/require"
)

func TestConvertLegacyToIOCopiesSpec(t *testing.T) {
	legacy := &k8gbv1beta1.Gslb{
		Spec: k8gbv1beta1.GslbSpec{
			Strategy: k8gbv1beta1.Strategy{Type: "roundRobin", DNSTtlSeconds: 30},
		},
	}

	io := convertGslbLegacyToIO(legacy)

	require.Equal(t, k8gbv1beta1io.GroupVersion.String(), io.APIVersion)
	require.Equal(t, "Gslb", io.Kind)
	require.Equal(t, legacy.Spec.Strategy.Type, io.Spec.Strategy.Type)
	require.Equal(t, legacy.Spec.Strategy.DNSTtlSeconds, io.Spec.Strategy.DNSTtlSeconds)
}
