package controllers

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"strings"

	"github.com/k8gb-io/k8gb/controllers/bootstrap"

	"github.com/k8gb-io/k8gb/controllers/zones"

	"github.com/k8gb-io/k8gb/controllers/providers/dns"
	"github.com/k8gb-io/k8gb/controllers/resolver"
	"github.com/k8gb-io/k8gb/controllers/utils"

	"go.opentelemetry.io/otel/trace"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/tools/record"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type CoreDNSReconciler struct {
	client.Client
	Config           *resolver.Config
	Recorder         record.EventRecorder
	Tracer           trace.Tracer
	Scheme           *runtime.Scheme
	DNSProvider      dns.Provider
	ZoneService      zones.ZoneDelegation
	BootstrapService *bootstrap.BoundIPsServiceImpl
}

// This reconciliation loop waits for external IPs to become available.
// Once detected, it creates default ZoneDelegation resources
// based on the configured delegation zones.
func (r *CoreDNSReconciler) Reconcile(ctx context.Context, _ ctrl.Request) (ctrl.Result, error) {
	// todo: introduce variable for reconciliation interval
	var err error
	result := utils.NewReconcileResultHandler(0)
	log.Info().Msg("Reconciling CoreDNS delegation")

	ips, err := r.BootstrapService.GetExposedIPs(ctx)
	if err != nil {
		logger.Err(err).Msg("Error listing zones")
		return result.Stop()
	}

	log.Info().Msgf("available IPs: [%s]", strings.Join(ips.IPs, ","))
	if len(ips.IPs) == 0 {
		log.Info().Msg("Waiting for IPs to be assigned.")
		return result.Stop()
	}

	// list existing ZoneDelegations and config DelegationZones
	zd, err := r.ZoneService.ListAllZoneDelegations(ctx)
	if err != nil {
		logger.Err(err).Msg("Error creating zone delegation")
		return result.RequeueError(err)
	}

	for _, zoneDelegation := range zd.Items {
		// save zoneDelegation and update coredns config map
		err = r.ZoneService.Save(ctx, &zoneDelegation)
		if err != nil {
			logger.Err(err).Msg("Error creating zone delegation")
			return result.RequeueError(err)
		}

		detail, err := zones.NewZoneDelegationWrapper(&zoneDelegation, r.Config, r.BootstrapService).GetDetail(ctx)
		if err != nil {
			logger.Err(err).Msg("Error creating zone delegation")
			return result.RequeueError(err)
		}

		// Create zoneDelegation in edge DNS
		err = r.DNSProvider.CreateZoneDelegation(detail)
		if err != nil {
			logger.Err(err).Msg("Error creating zone delegation")
		}
	}

	log.Info().
		Str("IPs", strings.Join(ips.IPs, ",")).
		Msg("CoreDNS delegation created")
	return result.Stop()
}
