package controllers

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"errors"
	"fmt"
	"reflect"

	k8gbv1beta1 "github.com/k8gb-io/k8gb/api/v1beta1"
	k8gbv1beta1io "github.com/k8gb-io/k8gb/api/v1beta1io"
	"github.com/k8gb-io/k8gb/controllers/providers/k8gbendpoint"
	"github.com/k8gb-io/k8gb/controllers/refresolver"
	"github.com/k8gb-io/k8gb/controllers/resolver"
	"github.com/k8gb-io/k8gb/controllers/utils"
	corev1 "k8s.io/api/core/v1"
	netv1 "k8s.io/api/networking/v1"
	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/tools/record"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	externaldnsApi "sigs.k8s.io/external-dns/apis/v1alpha1"
)

// LegacyGslbReconciler keeps legacy apiGroup runtime behavior active until migration is explicitly requested.
type LegacyGslbReconciler struct {
	client.Client
	Scheme   *runtime.Scheme
	Config   *resolver.Config
	Recorder record.EventRecorder
}

// Reconcile runs legacy runtime reconciliation only for legacy objects that are not migration requested/migrated yet.
func (r *LegacyGslbReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	result := utils.NewReconcileResultHandler(r.Config.ReconcileRequeueSeconds)

	legacy := &k8gbv1beta1.Gslb{}
	if err := r.Get(ctx, req.NamespacedName, legacy); err != nil {
		if k8serrors.IsNotFound(err) {
			return result.Stop()
		}
		return result.RequeueError(fmt.Errorf("error reading the legacy object (%s)", err))
	}

	if legacy.DeletionTimestamp != nil {
		return result.Stop()
	}

	// Migration flow ownership: do not reconcile legacy runtime when migration was requested/completed.
	if hasTrueLabel(legacy.Labels, migrationRequestLabelKey) || hasTrueLabel(legacy.Labels, migrationLabelKey) {
		return result.Stop()
	}

	gslb := convertGslbLegacyToIORuntime(legacy)
	if gslb.Spec.Strategy.DNSTtlSeconds == 0 {
		gslb.Spec.Strategy.DNSTtlSeconds = resolver.DefaultTTLSeconds
	}

	// Embedded mode only: create and own Ingress from legacy GSLB.
	if reflect.DeepEqual(gslb.Spec.ResourceRef, k8gbv1beta1io.ResourceRef{}) {
		ingress, err := r.createIngressFromLegacyGslb(legacy)
		if err != nil {
			m.IncrementError(gslb)
			return result.RequeueError(err)
		}
		if err = r.saveDependentLegacyIngress(ctx, legacy, ingress); err != nil {
			m.IncrementError(gslb)
			return result.RequeueError(err)
		}
	}

	refResolver, err := refresolver.New(gslb, r.Client)
	if err != nil {
		m.IncrementError(gslb)
		return result.RequeueError(fmt.Errorf("error resolving references (%s)", err))
	}
	servers, err := refResolver.GetServers()
	if err != nil {
		m.IncrementError(gslb)
		return result.RequeueError(fmt.Errorf("getting GSLB servers (%s)", err))
	}
	filteredServers := filterServersByDelegationZones(servers, r.Config.DelegationZones)
	if len(filteredServers) == 0 {
		return result.RequeueError(fmt.Errorf("no hosts match delegated zones %v", r.Config.DelegationZones.ListZones()))
	}
	gslb.Status.Servers = filteredServers

	loadBalancerExposedIPs, err := refResolver.GetGslbExposedIPs(legacy.Annotations, r.Config.ParentZoneDNSServers)
	if err != nil {
		m.IncrementError(gslb)
		errorMsg := fmt.Sprintf("getting load balancer exposed IPs (%s)", err)
		r.Recorder.Event(legacy, corev1.EventTypeWarning, "ExposedIPResolutionError", errorMsg)
		return result.RequeueError(errors.New(errorMsg))
	}
	lbIPv4Addresses, _ := splitIPsByVersion(loadBalancerExposedIPs)
	gslb.Status.LoadBalancer.ExposedIPs = lbIPv4Addresses

	serviceHealth, err := calculateServiceHealth(ctx, r.Client, gslb)
	if err != nil {
		m.IncrementError(gslb)
		return result.RequeueError(err)
	}
	gslb.Status.ServiceHealth = serviceHealth

	epProvider := k8gbendpoint.NewApplicationDNSEndpoint(
		context.TODO(),
		r.Client,
		r.Config,
		gslb,
		log,
		utils.NewDNSQueryService(),
		r.updateLegacyRuntimeStatus)

	dnsEndpoint, err := epProvider.GetDNSEndpoint()
	if err != nil {
		m.IncrementError(gslb)
		return result.RequeueError(err)
	}
	if err = controllerutil.SetControllerReference(legacy, dnsEndpoint, r.Scheme); err != nil {
		m.IncrementError(gslb)
		return result.RequeueError(err)
	}
	if err = epProvider.SaveDNSEndpoint(dnsEndpoint); err != nil {
		m.IncrementError(gslb)
		return result.RequeueError(err)
	}

	gslb.Status.HealthyRecords = collectHealthyRecordsFromDNSEndpoint(dnsEndpoint)
	gslb.Status.GeoTag = r.Config.ClusterGeoTag
	gslb.Status.Hosts = serversHostsToCSV(gslb)

	m.UpdateIngressHostsPerStatusMetric(gslb, gslb.Status.ServiceHealth)
	m.UpdateHealthyRecordsMetric(gslb, gslb.Status.HealthyRecords)
	m.UpdateHealthyLocalRecordsMetric(gslb, gslb.Status.HealthyRecords, gslb.Status.LoadBalancer.ExposedIPs)
	m.UpdateEndpointStatus(dnsEndpoint)

	legacy.Status = statusIOToLegacy(gslb.Status)
	if err = r.Status().Update(ctx, legacy); err != nil {
		m.IncrementError(gslb)
		return result.RequeueError(err)
	}

	m.IncrementReconciliation(gslb)
	return result.Requeue()
}

func (r *LegacyGslbReconciler) updateLegacyRuntimeStatus(
	gslb *k8gbv1beta1io.Gslb,
	isPrimary bool,
	isHealthy k8gbv1beta1io.HealthStatus,
	finalTargets []string,
) {
	updateRuntimeStatusMetrics(gslb, isPrimary, isHealthy, finalTargets)
}

func (r *LegacyGslbReconciler) createIngressFromLegacyGslb(gslb *k8gbv1beta1.Gslb) (*netv1.Ingress, error) {
	ingress := &netv1.Ingress{
		ObjectMeta: metav1.ObjectMeta{
			Name:      gslb.Name,
			Namespace: gslb.Namespace,
		},
		Spec: k8gbv1beta1.ToV1IngressSpec(gslb.Spec.Ingress),
	}
	utils.SetCommonGslbLabels(ingress)
	if err := controllerutil.SetControllerReference(gslb, ingress, r.Scheme); err != nil {
		return nil, err
	}
	return ingress, nil
}

func (r *LegacyGslbReconciler) saveDependentLegacyIngress(ctx context.Context, instance *k8gbv1beta1.Gslb, ingress *netv1.Ingress) error {
	found := &netv1.Ingress{}
	err := r.Get(ctx, types.NamespacedName{
		Name:      instance.Name,
		Namespace: instance.Namespace,
	}, found)
	if err != nil && k8serrors.IsNotFound(err) {
		return r.Create(ctx, ingress)
	} else if err != nil {
		return err
	}

	if !ingressEqual(found, ingress) {
		found.Spec = ingress.Spec
		utils.SetCommonGslbLabels(found)
		err = r.Update(ctx, found)
		if k8serrors.IsConflict(err) {
			return nil
		}
		return err
	}
	return nil
}

func statusIOToLegacy(status k8gbv1beta1io.GslbStatus) k8gbv1beta1.GslbStatus {
	return k8gbv1beta1.GslbStatus{
		ServiceHealth:  healthMapIOToLegacy(status.ServiceHealth),
		HealthyRecords: status.HealthyRecords,
		GeoTag:         status.GeoTag,
		Hosts:          status.Hosts,
		LoadBalancer: k8gbv1beta1.LoadBalancer{
			ExposedIPs: status.LoadBalancer.ExposedIPs,
		},
		Servers: serversIOToLegacy(status.Servers),
	}
}

func healthMapIOToLegacy(in map[string]k8gbv1beta1io.HealthStatus) map[string]k8gbv1beta1.HealthStatus {
	out := make(map[string]k8gbv1beta1.HealthStatus, len(in))
	for host, status := range in {
		out[host] = k8gbv1beta1.HealthStatus(status)
	}
	return out
}

func serversIOToLegacy(in []*k8gbv1beta1io.Server) []*k8gbv1beta1.Server {
	out := make([]*k8gbv1beta1.Server, 0, len(in))
	for _, server := range in {
		if server == nil {
			continue
		}
		legacyServer := &k8gbv1beta1.Server{
			Host:     server.Host,
			Services: make([]*k8gbv1beta1.NamespacedName, 0, len(server.Services)),
		}
		for _, service := range server.Services {
			if service == nil {
				continue
			}
			legacyServer.Services = append(legacyServer.Services, &k8gbv1beta1.NamespacedName{
				Namespace: service.Namespace,
				Name:      service.Name,
			})
		}
		out = append(out, legacyServer)
	}
	return out
}

func (r *LegacyGslbReconciler) SetupWithManager(mgr ctrl.Manager) error {
	r.Recorder = mgr.GetEventRecorderFor("legacy-gslb-controller")
	return ctrl.NewControllerManagedBy(mgr).
		Named("legacy-gslb-controller").
		For(&k8gbv1beta1.Gslb{}).
		Owns(&netv1.Ingress{}).
		Owns(&externaldnsApi.DNSEndpoint{}).
		Complete(r)
}
