package controllers

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"strings"

	k8gbv1beta1io "github.com/k8gb-io/k8gb/api/v1beta1io"
	"github.com/k8gb-io/k8gb/controllers/resolver"
	corev1 "k8s.io/api/core/v1"
	discov1 "k8s.io/api/discovery/v1"
	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	"sigs.k8s.io/controller-runtime/pkg/client"
	externaldnsApi "sigs.k8s.io/external-dns/apis/v1alpha1"
)

func updateRuntimeStatusMetrics(
	gslb *k8gbv1beta1io.Gslb,
	isPrimary bool,
	isHealthy k8gbv1beta1io.HealthStatus,
	finalTargets []string,
) {
	switch gslb.Spec.Strategy.Type {
	case resolver.RoundRobinStrategy:
		m.UpdateRoundrobinStatus(gslb, isHealthy, finalTargets)
	case resolver.GeoStrategy:
		m.UpdateGeoIPStatus(gslb, isHealthy, finalTargets)
	case resolver.FailoverStrategy:
		m.UpdateFailoverStatus(gslb, isPrimary, isHealthy, finalTargets)
	}
}

func calculateServiceHealth(
	ctx context.Context,
	c client.Client,
	gslb *k8gbv1beta1io.Gslb,
) (map[string]k8gbv1beta1io.HealthStatus, error) {
	serviceHealth := make(map[string]k8gbv1beta1io.HealthStatus)
	policy := effectiveServiceHealthPolicy(gslb)
	for _, server := range gslb.Status.Servers {
		if len(server.Services) == 0 {
			serviceHealth[server.Host] = k8gbv1beta1io.NotFound
			continue
		}

		healthyCount := 0
		unhealthyCount := 0
		notFoundCount := 0

		for _, svc := range server.Services {
			service := &corev1.Service{}
			finder := client.ObjectKey{
				Namespace: svc.Namespace,
				Name:      svc.Name,
			}
			err := c.Get(ctx, finder, service)
			if err != nil {
				if k8serrors.IsNotFound(err) {
					notFoundCount++
					continue
				}
				return serviceHealth, err
			}

			endpoints := &discov1.EndpointSliceList{}
			err = c.List(
				ctx,
				endpoints,
				client.InNamespace(svc.Namespace),
				client.MatchingLabels{discov1.LabelServiceName: svc.Name},
			)
			if err != nil {
				return serviceHealth, err
			}

			healthy := false
			if len(endpoints.Items) > 0 && len(endpoints.Items[0].Endpoints) > 0 {
				for _, endpoint := range endpoints.Items[0].Endpoints {
					if len(endpoint.Addresses) > 0 &&
						(endpoint.Conditions.Ready == nil || *endpoint.Conditions.Ready) {
						healthy = true
						break
					}
				}
			}

			if !healthy {
				unhealthyCount++
				continue
			}

			healthyCount++
		}

		serviceHealth[server.Host] = calculateHostHealth(policy, healthyCount, unhealthyCount, notFoundCount)
	}
	return serviceHealth, nil
}

func effectiveServiceHealthPolicy(gslb *k8gbv1beta1io.Gslb) k8gbv1beta1io.ServiceHealthPolicy {
	if gslb.Spec.ServiceHealthPolicy == k8gbv1beta1io.ServiceHealthPolicyAll {
		return k8gbv1beta1io.ServiceHealthPolicyAll
	}
	return k8gbv1beta1io.ServiceHealthPolicyAny
}

func calculateHostHealth(
	policy k8gbv1beta1io.ServiceHealthPolicy,
	healthyCount int,
	unhealthyCount int,
	notFoundCount int,
) k8gbv1beta1io.HealthStatus {
	switch policy {
	case k8gbv1beta1io.ServiceHealthPolicyAll:
		if notFoundCount > 0 {
			return k8gbv1beta1io.NotFound
		}
		if unhealthyCount > 0 {
			return k8gbv1beta1io.Unhealthy
		}
		return k8gbv1beta1io.Healthy
	default:
		if healthyCount > 0 {
			return k8gbv1beta1io.Healthy
		}
		if unhealthyCount > 0 {
			return k8gbv1beta1io.Unhealthy
		}
		return k8gbv1beta1io.NotFound
	}
}

func collectHealthyRecordsFromDNSEndpoint(dnsEndpoint *externaldnsApi.DNSEndpoint) map[string][]string {
	healthyRecords := make(map[string][]string)
	if dnsEndpoint == nil {
		return healthyRecords
	}
	for _, endpoint := range dnsEndpoint.Spec.Endpoints {
		if strings.HasPrefix(endpoint.DNSName, "localtargets") {
			continue
		}
		if endpoint.RecordType == "A" && len(endpoint.Targets) > 0 {
			healthyRecords[endpoint.DNSName] = endpoint.Targets
		}
	}
	return healthyRecords
}

func serversHostsToCSV(gslb *k8gbv1beta1io.Gslb) string {
	var hosts []string
	for _, server := range gslb.Status.Servers {
		hosts = append(hosts, server.Host)
	}
	return strings.Join(hosts, ", ")
}
