{
 "title": "Custom-Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(k8gb_gslb_service_status_num{namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(k8gb_gslb_service_status_num, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(k8gb_gslb_service_status_num{namespace=~\"$namespace\", job=~\"$job\"}, pod)"
    }
   },
   {
    "name": "gslb",
    "query": {
     "query": "label_values(k8gb_gslb_service_status_num{namespace=~\"$namespace\"}, exported_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total errors per minute (counter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(k8gb_gslb_errors_total{namespace=~\"$namespace\", job=\"$job\"}[5m])*5*60) by (namespace)",
     "legendFormat": "namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Total errors per gslb per minute (counter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(k8gb_gslb_errors_total{namespace=~\"$namespace\", job=\"$job\", exported_name=\"$gslb\"}[5m])*5*60) by (exported_name)",
     "legendFormat": "gslb: {{exported_name}}"
    }
   ]
  },
  {
   "title": "Number of IPs (targets) per dns record (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k8gb_endpoint_status_num{namespace=~\"$namespace\", job=\"$job\"}) by (dns_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Service status of gslb (gauge)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k8gb_gslb_service_status_num{namespace=~\"$namespace\", job=\"$job\", exported_name=\"$gslb\"}) by (status)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "k8gb_runtime_info (info)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "k8gb_runtime_info" }
   ]
  }
 ]
}