package zones

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"sort"

	"github.com/k8gb-io/k8gb/api/v1beta1io"
	"github.com/k8gb-io/k8gb/controllers/ipresolver"
	"github.com/k8gb-io/k8gb/controllers/resolver"
	"github.com/k8gb-io/k8gb/controllers/utils"
)

// ZoneDelegationWrapper extends ZoneDelegation object for properties required by k8gb ekosystem (ApplicationDNSEndpoint etc)
type ZoneDelegationWrapper struct {
	zoneDelegation *v1beta1io.ZoneDelegation
	config         *resolver.Config
	ipr            ipresolver.Resolver
}

type ExtendedZoneDelegation struct {
	wrapper          *ZoneDelegationWrapper
	LoadBalancedZone string
	ParentZone       string
	NegativeTTL      int
	ClusterNSName    string
	// TODO: use directly GetExposedIPs(ctx) on places where LocalCoreDNSExposedIPs are required
	LocalCoreDNSExposedIPs ZoneDelegationIPs
	name                   string
}

func NewZoneDelegationWrapper(
	zoneDelegation *v1beta1io.ZoneDelegation,
	config *resolver.Config,
	bootstrap ipresolver.Resolver) *ZoneDelegationWrapper {
	return &ZoneDelegationWrapper{zoneDelegation: zoneDelegation, config: config, ipr: bootstrap}
}

func (z *ZoneDelegationWrapper) GetDetail(ctx context.Context) (*ExtendedZoneDelegation, error) {

	validateRFC1035 := func(zd *v1beta1io.ZoneDelegation) error {
		for _, ns := range z.config.GetClusterNsNames(zd).GetNSServerList() {
			if err := utils.ValidateRFC1035(ns); err != nil {
				return err
			}
		}
		return nil
	}

	ips, err := z.ipr.GetExposedIPs(ctx)
	if err != nil {
		return nil, err
	}
	zoneDetail := &ExtendedZoneDelegation{
		wrapper:                z,
		name:                   z.zoneDelegation.Name,
		LoadBalancedZone:       z.zoneDelegation.Spec.LoadBalancedZone,
		ParentZone:             z.zoneDelegation.Spec.ParentZone,
		NegativeTTL:            z.zoneDelegation.Spec.DNSZoneNegTTL,
		ClusterNSName:          z.config.GetClusterNSName(*z.zoneDelegation),
		LocalCoreDNSExposedIPs: ZoneDelegationIPs(ips.IPs),
	}
	err = validateRFC1035(z.zoneDelegation)
	if err != nil {
		return nil, err
	}
	return zoneDetail, nil
}

// GetActiveNSServerList returns NS names from ZoneDelegation status (resolved
// glue). Status is built from static config or dynamic DNS discovery, so this
// must not intersect with Helm extGslbClustersGeoTags or dynamically
// discovered peers are dropped from the published NS RRset.
func (d *ExtendedZoneDelegation) GetActiveNSServerList() []string {
	seen := map[string]struct{}{}
	var result []string
	for _, glueA := range d.wrapper.zoneDelegation.Status.DNSServers {
		if glueA.Name == "" {
			continue
		}
		if _, found := seen[glueA.Name]; found {
			continue
		}
		seen[glueA.Name] = struct{}{}
		result = append(result, glueA.Name)
	}
	sort.Strings(result)
	return result
}

func (d *ExtendedZoneDelegation) GetZoneDelegation() *v1beta1io.ZoneDelegation {
	return d.wrapper.zoneDelegation.DeepCopy()
}

func (d *ExtendedZoneDelegation) Name() string {
	return d.name
}

func (d *ExtendedZoneDelegation) IsLastZoneDelegationResource() bool {
	servers := d.wrapper.zoneDelegation.Status.DNSServers
	if len(servers) == 0 {
		return false
	}

	for _, server := range servers {
		if server.Name != d.ClusterNSName {
			return false
		}
	}

	return true
}
