package zones

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/k8gb-io/k8gb/controllers/ipresolver"

	"github.com/k8gb-io/k8gb/api/k8gb.io/v1beta1"
	"github.com/k8gb-io/k8gb/controllers/resolver"
)

// ZoneDelegationWrapper extends ZoneDelegation object for properties required by k8gb ekosystem (ApplicationDNSEndpoint etc)
type ZoneDelegationWrapper struct {
	zoneDelegation *v1beta1.ZoneDelegation
	config         *resolver.Config
	ipr            ipresolver.Resolver
}

type ExtendedZoneDelegation struct {
	wrapper           *ZoneDelegationWrapper
	LoadBalancedZone  string
	ParentZone        string
	NegativeTTL       int
	ClusterNSName     string
	ExtClusterNSNames map[string]string
	IPs               ZoneDelegationIPs
}

func NewZoneDelegationWrapper(
	zoneDelegation *v1beta1.ZoneDelegation,
	config *resolver.Config,
	bootstrap ipresolver.Resolver) *ZoneDelegationWrapper {
	return &ZoneDelegationWrapper{zoneDelegation: zoneDelegation, config: config, ipr: bootstrap}
}

func (z *ZoneDelegationWrapper) GetDetail(ctx context.Context) (*ExtendedZoneDelegation, error) {

	validateRFC1035 := func(detail *ExtendedZoneDelegation) error {
		const dnsNameMax = 253
		const dnsLabelMax = 63
		for _, ns := range detail.GetNSServerList() {
			if len(ns) > dnsNameMax {
				return fmt.Errorf("%s exceeds %v characters limit", ns, dnsNameMax)
			}
			labels := strings.Split(ns, ".")
			for _, l := range labels {
				if len(l) > dnsLabelMax {
					return fmt.Errorf("label %s in %s exceeds %v characters limit", l, ns, dnsLabelMax)
				}
			}
		}
		return nil
	}

	ips, err := z.ipr.GetExposedIPs(ctx)
	if err != nil {
		return nil, err
	}
	zoneDetail := &ExtendedZoneDelegation{
		wrapper:           z,
		LoadBalancedZone:  z.zoneDelegation.Spec.LoadBalancedZone,
		ParentZone:        z.zoneDelegation.Spec.ParentZone,
		NegativeTTL:       z.zoneDelegation.Spec.DNSZoneNegTTL,
		ClusterNSName:     getNsName(z.config.ClusterGeoTag, z.zoneDelegation.Spec.LoadBalancedZone, z.zoneDelegation.Spec.ParentZone),
		ExtClusterNSNames: z.config.GetExtClusterNSNames(z.zoneDelegation.Spec.LoadBalancedZone, z.zoneDelegation.Spec.ParentZone),
		IPs:               ZoneDelegationIPs(ips.IPs),
	}
	err = validateRFC1035(zoneDetail)
	if err != nil {
		return nil, err
	}
	return zoneDetail, nil
}

// GetNSServerList returns a sorted list of all NS servers for the delegation zone
func (d *ExtendedZoneDelegation) GetNSServerList() []string {
	list := []string{d.ClusterNSName}
	for _, v := range d.ExtClusterNSNames {
		list = append(list, v)
	}
	sort.Strings(list)
	return list
}

// GetExternalDNSEndpointName returns name of endpoint sitting in k8gb namespace
func (d *ExtendedZoneDelegation) GetExternalDNSEndpointName() string {
	var suffix = strings.Trim(strings.ReplaceAll(d.LoadBalancedZone, ".", "-"), " ")
	return fmt.Sprintf("k8gb-ns-extdns-%s", suffix)
}

func (d *ExtendedZoneDelegation) GetNSName(tag string) string {
	return getNsName(tag, d.LoadBalancedZone, d.ParentZone)
}

func getNsName(tag, zone, edge string) string {
	const prefix = "gslb-ns"
	d := strings.TrimSuffix(zone, "."+edge)
	domainX := strings.ReplaceAll(d, ".", "-")
	return fmt.Sprintf("%s-%s-%s.%s", prefix, tag, domainX, edge)
}
