package zones

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"

	"github.com/k8gb-io/k8gb/api/v1beta1io"
	"github.com/k8gb-io/k8gb/controllers/ipresolver"
	"github.com/k8gb-io/k8gb/controllers/resolver"
	"github.com/k8gb-io/k8gb/controllers/utils"
)

// ZoneDelegationWrapper extends ZoneDelegation object for properties required by k8gb ekosystem (ApplicationDNSEndpoint etc)
type ZoneDelegationWrapper struct {
	zoneDelegation *v1beta1io.ZoneDelegation
	config         *resolver.Config
	ipr            ipresolver.Resolver
}

type ExtendedZoneDelegation struct {
	wrapper           *ZoneDelegationWrapper
	LoadBalancedZone  string
	ParentZone        string
	NegativeTTL       int
	ClusterNSName     string
	ExtClusterNSNames resolver.ClusterNSNames
	// TODO: use directly GetExposedIPs(ctx) on places where LocalCoreDNSExposedIPs are required
	LocalCoreDNSExposedIPs ZoneDelegationIPs
	name                   string
}

func NewZoneDelegationWrapper(
	zoneDelegation *v1beta1io.ZoneDelegation,
	config *resolver.Config,
	bootstrap ipresolver.Resolver) *ZoneDelegationWrapper {
	return &ZoneDelegationWrapper{zoneDelegation: zoneDelegation, config: config, ipr: bootstrap}
}

func (z *ZoneDelegationWrapper) GetDetail(ctx context.Context) (*ExtendedZoneDelegation, error) {

	validateRFC1035 := func(zd *v1beta1io.ZoneDelegation) error {
		for _, ns := range z.config.GetClusterNsNames(zd).GetNSServerList() {
			if err := utils.ValidateRFC1035(ns); err != nil {
				return err
			}
		}
		return nil
	}

	ips, err := z.ipr.GetExposedIPs(ctx)
	if err != nil {
		return nil, err
	}
	zoneDetail := &ExtendedZoneDelegation{
		wrapper:                z,
		name:                   z.zoneDelegation.Name,
		LoadBalancedZone:       z.zoneDelegation.Spec.LoadBalancedZone,
		ParentZone:             z.zoneDelegation.Spec.ParentZone,
		NegativeTTL:            z.zoneDelegation.Spec.DNSZoneNegTTL,
		ClusterNSName:          z.config.GetClusterNSName(*z.zoneDelegation),
		ExtClusterNSNames:      z.config.GetClusterNsNames(z.zoneDelegation).ExtClusterNsNames(),
		LocalCoreDNSExposedIPs: ZoneDelegationIPs(ips.IPs),
	}
	err = validateRFC1035(z.zoneDelegation)
	if err != nil {
		return nil, err
	}
	return zoneDetail, nil
}

// GetActiveNSServerList returns only NS servers that are currently present
// in the ZoneDelegation status and considered active/reachable.
func (d *ExtendedZoneDelegation) GetActiveNSServerList() []string {
	zoneList := map[string]bool{}
	fullList := d.wrapper.config.GetClusterNsNames(d.GetZoneDelegation()).GetNSServerList()
	var result []string
	if len(d.wrapper.zoneDelegation.Status.DNSServers) == 0 {
		return result
	}
	for _, glueA := range d.wrapper.zoneDelegation.Status.DNSServers {
		zoneList[glueA.Name] = true
	}
	for _, ns := range fullList {
		if _, found := zoneList[ns]; found {
			result = append(result, ns)
		}
	}
	return result
}

func (d *ExtendedZoneDelegation) GetZoneDelegation() *v1beta1io.ZoneDelegation {
	return d.wrapper.zoneDelegation.DeepCopy()
}

func (d *ExtendedZoneDelegation) Name() string {
	return d.name
}

func (d *ExtendedZoneDelegation) IsLastZoneDelegationResource() bool {
	servers := d.wrapper.zoneDelegation.Status.DNSServers
	if len(servers) == 0 {
		return false
	}

	for _, server := range servers {
		if server.Name != d.ClusterNSName {
			return false
		}
	}

	return true
}
