// Code generated by MockGen. DO NOT EDIT.
// Source: controllers/zones/zone_service.go
//
// Generated by this command:
//
//	mockgen -package=zones -destination=controllers/zones/zone_delegation_service_mock.go -source=controllers/zones/zone_service.go ZoneDelegationService
//

// Package zones is a generated GoMock package.
package zones

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	context "context"
	reflect "reflect"

	v1beta1 "github.com/k8gb-io/k8gb/api/k8gb.io/v1beta1"
	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockZoneDelegation is a mock of ZoneDelegation interface.
type MockZoneDelegation struct {
	ctrl     *gomock.Controller
	recorder *MockZoneDelegationMockRecorder
}

// MockZoneDelegationMockRecorder is the mock recorder for MockZoneDelegation.
type MockZoneDelegationMockRecorder struct {
	mock *MockZoneDelegation
}

// NewMockZoneDelegation creates a new mock instance.
func NewMockZoneDelegation(ctrl *gomock.Controller) *MockZoneDelegation {
	mock := &MockZoneDelegation{ctrl: ctrl}
	mock.recorder = &MockZoneDelegationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZoneDelegation) EXPECT() *MockZoneDelegationMockRecorder {
	return m.recorder
}

// AvailableIPs mocks base method.
func (m *MockZoneDelegation) AvailableIPs(ctx context.Context) (ZoneDelegationIPs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvailableIPs", ctx)
	ret0, _ := ret[0].(ZoneDelegationIPs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AvailableIPs indicates an expected call of AvailableIPs.
func (mr *MockZoneDelegationMockRecorder) AvailableIPs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvailableIPs", reflect.TypeOf((*MockZoneDelegation)(nil).AvailableIPs), ctx)
}

// Get mocks base method.
func (m *MockZoneDelegation) Get(ctx context.Context, objKey client.ObjectKey) (*v1beta1.ZoneDelegation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, objKey)
	ret0, _ := ret[0].(*v1beta1.ZoneDelegation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockZoneDelegationMockRecorder) Get(ctx, objKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockZoneDelegation)(nil).Get), ctx, objKey)
}

// HasAvailableIPs mocks base method.
func (m *MockZoneDelegation) HasAvailableIPs(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAvailableIPs", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasAvailableIPs indicates an expected call of HasAvailableIPs.
func (mr *MockZoneDelegationMockRecorder) HasAvailableIPs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAvailableIPs", reflect.TypeOf((*MockZoneDelegation)(nil).HasAvailableIPs), ctx)
}

// HasExtClusterGeoTags mocks base method.
func (m *MockZoneDelegation) HasExtClusterGeoTags(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasExtClusterGeoTags", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasExtClusterGeoTags indicates an expected call of HasExtClusterGeoTags.
func (mr *MockZoneDelegationMockRecorder) HasExtClusterGeoTags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasExtClusterGeoTags", reflect.TypeOf((*MockZoneDelegation)(nil).HasExtClusterGeoTags), ctx)
}

// List mocks base method.
func (m *MockZoneDelegation) List(ctx context.Context) (*v1beta1.ZoneDelegationList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(*v1beta1.ZoneDelegationList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockZoneDelegationMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockZoneDelegation)(nil).List), ctx)
}

// ListAllZoneDelegations mocks base method.
func (m *MockZoneDelegation) ListAllZoneDelegations(ctx context.Context) (*v1beta1.ZoneDelegationList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllZoneDelegations", ctx)
	ret0, _ := ret[0].(*v1beta1.ZoneDelegationList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllZoneDelegations indicates an expected call of ListAllZoneDelegations.
func (mr *MockZoneDelegationMockRecorder) ListAllZoneDelegations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllZoneDelegations", reflect.TypeOf((*MockZoneDelegation)(nil).ListAllZoneDelegations), ctx)
}

// ListConfigZoneDelegations mocks base method.
func (m *MockZoneDelegation) ListConfigZoneDelegations(ctx context.Context) (*v1beta1.ZoneDelegationList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfigZoneDelegations", ctx)
	ret0, _ := ret[0].(*v1beta1.ZoneDelegationList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfigZoneDelegations indicates an expected call of ListConfigZoneDelegations.
func (mr *MockZoneDelegationMockRecorder) ListConfigZoneDelegations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfigZoneDelegations", reflect.TypeOf((*MockZoneDelegation)(nil).ListConfigZoneDelegations), ctx)
}

// Save mocks base method.
func (m *MockZoneDelegation) Save(ctx context.Context, z *v1beta1.ZoneDelegation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, z)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockZoneDelegationMockRecorder) Save(ctx, z any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockZoneDelegation)(nil).Save), ctx, z)
}

// UpdateStatus mocks base method.
func (m *MockZoneDelegation) UpdateStatus(ctx context.Context, zd *v1beta1.ZoneDelegation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, zd)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockZoneDelegationMockRecorder) UpdateStatus(ctx, zd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockZoneDelegation)(nil).UpdateStatus), ctx, zd)
}
