package v1beta1

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ZoneDelegationSpec defines the desired state of ZoneDelegation

type ZoneDelegationSpec struct {
	// LoadBalancedZone is the DNS zone managed by this ZoneDelegation
	LoadBalancedZone string `json:"loadBalancedZone"`

	// ParentZone is the zone under which this load-balanced zone is delegated
	ParentZone string `json:"parentZone"`

	// DNSZoneNegTTL specifies the negative TTL for the DNS zone (in seconds)
	DNSZoneNegTTL int `json:"dnsZoneNegTTL"`
}

// ZoneDelegationStatus defines the observed state of ZoneDelegation
type ZoneDelegationStatus struct {
	// DNSServers lists the authoritative DNS servers for the delegated zone
	DNSServers []DNSServer `json:"dnsServers,omitempty"`
}

// DNSServer represents a single DNS server for a zone delegation
type DNSServer struct {
	// Name of the DNS server (FQDN)
	Name string `json:"name"`

	// Address of the DNS server (IPv4 or IPv6)
	Address string `json:"address"`
}

// ZoneDelegation is the Schema for the zonedelegations API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=zd
// +kubebuilder:printcolumn:name="LoadBalancedZone",type=string,JSONPath=`.spec.loadBalancedZone`
// +kubebuilder:printcolumn:name="ParentZone",type=string,JSONPath=`.spec.parentZone`
// +kubebuilder:printcolumn:name="NegTTL",type=integer,JSONPath=`.spec.dnsZoneNegTTL`
type ZoneDelegation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ZoneDelegationSpec   `json:"spec,omitempty"`
	Status ZoneDelegationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZoneDelegationList contains a list of ZoneDelegation
type ZoneDelegationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZoneDelegation `json:"items"`
}
