---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multiservice-blue-nginx
  namespace: test-gslb
data:
  default.conf: |
    server {
      listen 8080;

      location / {
        default_type text/plain;
        return 200 "k8gb multiservice blue\n";
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multiservice-green-nginx
  namespace: test-gslb
data:
  default.conf: |
    server {
      listen 8080;

      location / {
        default_type text/plain;
        return 200 "k8gb multiservice green\n";
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiservice-blue
  namespace: test-gslb
  labels:
    app.kubernetes.io/name: multiservice-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: multiservice-blue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: multiservice-blue
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: multiservice-blue-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiservice-green
  namespace: test-gslb
  labels:
    app.kubernetes.io/name: multiservice-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: multiservice-green
  template:
    metadata:
      labels:
        app.kubernetes.io/name: multiservice-green
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: multiservice-green-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: multiservice-blue
  namespace: test-gslb
  labels:
    app.kubernetes.io/name: multiservice-blue
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: multiservice-blue
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: multiservice-green
  namespace: test-gslb
  labels:
    app.kubernetes.io/name: multiservice-green
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: multiservice-green
  ports:
  - name: http
    port: 80
    targetPort: http
