package gatewayapitcproute

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"testing"

	k8gbv1beta1io "github.com/k8gb-io/k8gb/api/v1beta1io"
	"github.com/k8gb-io/k8gb/controllers/utils"
	"github.com/stretchr/testify/assert"
)

func TestGetServers(t *testing.T) {
	var tests = []struct {
		name            string
		tcpRouteFile    string
		gslbAnnotations map[string]string
		expectedServers []*k8gbv1beta1io.Server
		expectError     bool
	}{
		{
			name:            "missing hostname annotation",
			tcpRouteFile:    "../testdata/gatewayapi_tcproute.yaml",
			gslbAnnotations: map[string]string{},
			expectedServers: nil,
			expectError:     true,
		},
		{
			name:         "empty hostname annotation",
			tcpRouteFile: "../testdata/gatewayapi_tcproute.yaml",
			gslbAnnotations: map[string]string{
				utils.HostnameAnnotation: "",
			},
			expectedServers: nil,
			expectError:     true,
		},
		{
			name:         "valid TCPRoute with hostname annotation; backend without namespace specified",
			tcpRouteFile: "../testdata/gatewayapi_tcproute.yaml",
			gslbAnnotations: map[string]string{
				utils.HostnameAnnotation: "gatewayapi-tcproute.cloud.example.com",
			},
			expectedServers: []*k8gbv1beta1io.Server{
				{
					Host: "gatewayapi-tcproute.cloud.example.com",
					Services: []*k8gbv1beta1io.NamespacedName{
						{
							Name:      "gatewayapi-tcproute-service",
							Namespace: "test-gslb",
						},
					},
				},
			},
		},
		{
			name:         "valid TCPRoute with hostname annotation; backend with namespace specified",
			tcpRouteFile: "./testdata/gatewayapi_tcproute_backend_with_namespace.yaml",
			gslbAnnotations: map[string]string{
				utils.HostnameAnnotation: "gatewayapi-tcproute.cloud.example.com",
			},
			expectedServers: []*k8gbv1beta1io.Server{
				{
					Host: "gatewayapi-tcproute.cloud.example.com",
					Services: []*k8gbv1beta1io.NamespacedName{
						{
							Name:      "gatewayapi-tcproute-service",
							Namespace: "test-backend",
						},
					},
				},
			},
		},
		{
			name:         "multiple backendRefs",
			tcpRouteFile: "./testdata/gatewayapi_tcproute_multiple_backendrefs.yaml",
			gslbAnnotations: map[string]string{
				utils.HostnameAnnotation: "gatewayapi-tcproute.cloud.example.com",
			},
			expectedServers: []*k8gbv1beta1io.Server{
				{
					Host: "gatewayapi-tcproute.cloud.example.com",
					Services: []*k8gbv1beta1io.NamespacedName{
						{
							Name:      "gatewayapi-tcproute-service1",
							Namespace: "test-gslb",
						},
						{
							Name:      "gatewayapi-tcproute-service2",
							Namespace: "test-gslb",
						},
					},
				},
			},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			// arrange
			tcpRoute := utils.FileToGatewayApiTcpRoute(test.tcpRouteFile)
			resolver := ReferenceResolver{
				route: NewTCPRouteAdapter(tcpRoute, test.gslbAnnotations[utils.HostnameAnnotation]),
			}

			// act
			servers, err := resolver.GetServers()

			// assert
			if test.expectError {
				assert.Error(t, err)
				assert.Nil(t, servers)
			} else {
				assert.NoError(t, err)
				assert.Equal(t, test.expectedServers, servers)
			}
		})
	}
}
