package dns

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"os"
	"testing"

	"github.com/k8gb-io/k8gb/controllers/depresolver"
	"github.com/stretchr/testify/assert"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	externaldns "sigs.k8s.io/external-dns/endpoint"
)

func TestCreateZoneDelegation(t *testing.T) {
	// arrange
	ctx := context.TODO()
	var cl client.Client
	var tests = []struct {
		name          string
		config        depresolver.Config
		expectedError bool
		init          func(cfg depresolver.Config)
	}{
		{
			name: "cloud.example.com",
			config: depresolver.Config{
				K8gbNamespace: "k8gb",
				NSRecordTTL:   60,
				DelegationZones: []*depresolver.DelegationZoneInfo{
					{
						Domain:        "cloud.example.com",
						Zone:          "example.com",
						NegativeTTL:   60,
						IPs:           []string{"10.0.0.1", "10.0.0.2"},
						ClusterNSName: "gslb-ns-eu-k8gb-test-gslb.cloud.example.com",
						ExtClusterNSNames: map[string]string{
							"us": "gslb-ns-us-k8gb-test-gslb.cloud.example.com",
						},
					},
				},
			},
			init: func(cfg depresolver.Config) {
				cl = fake.NewClientBuilder().WithScheme(scheme.Scheme).Build()
				_ = cl.Get(ctx, client.ObjectKey{Name: "k8gb-ns-extdns-cloud-example-com", Namespace: cfg.K8gbNamespace}, &externaldns.DNSEndpoint{})
				_ = cl.Get(ctx, client.ObjectKey{Name: "k8gb-ns-extdns-cloud-example-com", Namespace: cfg.K8gbNamespace}, &externaldns.DNSEndpoint{})
				_ = cl.Create(ctx, &externaldns.DNSEndpoint{
					ObjectMeta: metav1.ObjectMeta{
						Name:      "k8gb-ns-extdns-cloud-example-com",
						Namespace: cfg.K8gbNamespace},
				})
			},
			expectedError: false,
		},
	}

	// act
	// assert
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			test.init(test.config)
			externalDNSProvider := NewExternalDNS(ctx, cl, test.config)
			for _, zone := range test.config.DelegationZones {
				err := externalDNSProvider.CreateZoneDelegation(zone)
				assert.Equal(t, test.expectedError, err != nil)
			}
		})
	}
}

func TestMain(m *testing.M) {
	scheme.Scheme.AddKnownTypes(schema.GroupVersion{Group: "externaldns.k8s.io", Version: "v1alpha1"}, &externaldns.DNSEndpoint{})
	os.Exit(m.Run())
}
