package dns

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"strconv"

	ibclient "github.com/infobloxopen/infoblox-go-client"
	"github.com/k8gb-io/k8gb/controllers/depresolver"
)

type InfobloxClient interface {
	GetObjectManager() (objMgr *ibclient.ObjectManager, err error)
}

type Client struct {
	objMgr *ibclient.ObjectManager
	config depresolver.Config
}

func NewInfobloxClient(config depresolver.Config) *Client {
	return &Client{
		config: config,
	}
}

func (c *Client) GetObjectManager() (objMgr *ibclient.ObjectManager, err error) {
	hostConfig := ibclient.HostConfig{
		Host:     c.config.Infoblox.Host,
		Version:  c.config.Infoblox.Version,
		Port:     strconv.Itoa(c.config.Infoblox.Port),
		Username: c.config.Infoblox.Username,
		Password: c.config.Infoblox.Password,
	}
	transportConfig := ibclient.NewTransportConfig("false", c.config.Infoblox.HTTPRequestTimeout, c.config.Infoblox.HTTPPoolConnections)
	requestBuilder := &ibclient.WapiRequestBuilder{}
	requestor := &ibclient.WapiHttpRequestor{}
	conn, err := ibclient.NewConnector(hostConfig, transportConfig, requestBuilder, requestor)
	if err != nil {
		return
	}
	defer func() {
		err = conn.Logout()
	}()
	c.objMgr = ibclient.NewObjectManager(conn, "k8gbclient", "")
	return c.objMgr, nil
}
