package dns

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"fmt"
	"reflect"
	"time"

	"github.com/k8gb-io/k8gb/controllers/zones"

	ibcl "github.com/infobloxopen/infoblox-go-client/v2"
	"github.com/k8gb-io/k8gb/controllers/providers/metrics"
	"github.com/k8gb-io/k8gb/controllers/resolver"
	"k8s.io/apimachinery/pkg/api/errors"
)

type InfobloxProvider struct {
	config resolver.Config
	client InfobloxClient
}

var m = metrics.Metrics()

func NewInfobloxDNS(config resolver.Config, client InfobloxClient) *InfobloxProvider {
	return &InfobloxProvider{
		client: client,
		config: config,
	}
}

// current IP list is up to date, so we remove it from delegatedTo.
func (p *InfobloxProvider) sanitizeDelegateZone(local, upstream []ibcl.NameServer, zoneInfo *zones.ExtendedZoneDelegation) []ibcl.NameServer {
	// Drop own records for straight away update
	// And ensure local entries are up to date
	// And final list is sorted
	final := local
	remote := p.filterOutDelegateTo(upstream, zoneInfo.ClusterNSName)
	final = append(final, remote...)
	sortZones(final)

	return final
}

func (p *InfobloxProvider) CreateZoneDelegation(zoneInfo *zones.ExtendedZoneDelegation) error {
	objMgr, err := p.client.GetObjectManager()
	if err != nil {
		return err
	}
	findZone, err := p.getZoneDelegated(objMgr, zoneInfo.LoadBalancedZone)
	if err != nil {
		return err
	}

	var delegateTo []ibcl.NameServer
	for _, address := range zoneInfo.LocalCoreDNSExposedIPs.Sorted() {
		nameServer := ibcl.NameServer{Address: address, Name: zoneInfo.ClusterNSName}
		delegateTo = append(delegateTo, nameServer)
	}

	if findZone == nil {
		log.Info().
			Str("DNSZone", zoneInfo.LoadBalancedZone).
			Msg("Creating delegated zone")
		log.Debug().
			Interface("records", delegateTo).
			Msg("Delegated records")
		_, err = p.createZoneDelegated(objMgr, zoneInfo.LoadBalancedZone, delegateTo)
		if err != nil {
			return err
		}
		return nil
	}

	// if zone exists
	if len(findZone.Ref) > 0 {
		sortZones(findZone.DelegateTo.NameServers)
		currentList := p.sanitizeDelegateZone(delegateTo, findZone.DelegateTo.NameServers, zoneInfo)
		if !reflect.DeepEqual(findZone.DelegateTo.NameServers, currentList) {
			log.Info().
				Interface("records", findZone.DelegateTo).
				Msg("Found delegated zone records")
			log.Info().
				Str("DNSZone", zoneInfo.LoadBalancedZone).
				Interface("serverList", currentList).
				Msg("Updating delegated zone with the server list")
			_, err = p.updateZoneDelegated(objMgr, findZone.Ref, currentList)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func (p *InfobloxProvider) Finalize(zoneInfo *zones.ExtendedZoneDelegation, finalizeZone bool) error {
	objMgr, err := p.client.GetObjectManager()
	if err != nil {
		return err
	}

	// finalize LoadBalancedZone ( + GluA, SOA and NS records)
	if finalizeZone {
		log.Info().Msgf("Removing delegated zone %s from edge DNS", zoneInfo.LoadBalancedZone)
		return p.deleteZoneDelegated(objMgr, zoneInfo.LoadBalancedZone)
	}

	// finalize GlueA record only
	log.Info().Msgf("Removing Glue A %s records for delegated zone %s", zoneInfo.ClusterNSName, zoneInfo.LoadBalancedZone)
	return p.removeGlueAFromDelegatedZone(objMgr, zoneInfo.LoadBalancedZone, zoneInfo.ClusterNSName, zoneInfo.LocalCoreDNSExposedIPs)
}

func (p *InfobloxProvider) String() string {
	return "Infoblox"
}

func (p *InfobloxProvider) filterOutDelegateTo(delegateTo []ibcl.NameServer, fqdn string) (result []ibcl.NameServer) {
	result = make([]ibcl.NameServer, 0)

	for _, v := range delegateTo {
		if v.Name != fqdn {
			result = append(result, v)
		}
	}
	return
}

func (p *InfobloxProvider) createZoneDelegated(o ibcl.IBObjectManager, fqdn string, d []ibcl.NameServer) (res *ibcl.ZoneDelegated, err error) {
	start := time.Now()
	ns := ibcl.NullableNameServers{NameServers: d, IsNull: false}
	//nolint: gosec
	res, err = o.CreateZoneDelegated(fqdn, ns, "created by k8gb", false, false,
		"", uint32(p.config.NSRecordTTL), true, ibcl.EA{}, p.config.Infoblox.DNSView, "FORWARD")
	m.InfobloxObserveRequestDuration(start, metrics.CreateZoneDelegated, err == nil)
	return
}

func (p *InfobloxProvider) getZoneDelegated(o ibcl.IBObjectManager, fqdn string) (res *ibcl.ZoneDelegated, err error) {
	start := time.Now()
	res, err = o.GetZoneDelegated(fqdn)
	m.InfobloxObserveRequestDuration(start, metrics.GetZoneDelegated, err == nil)
	if err != nil && !errors.IsNotFound(err) {
		return nil, nil
	}
	return
}

func (p *InfobloxProvider) updateZoneDelegated(o ibcl.IBObjectManager, zoneRef string, d []ibcl.NameServer) (res *ibcl.ZoneDelegated, err error) {
	start := time.Now()
	ns := ibcl.NullableNameServers{NameServers: d, IsNull: false}
	//nolint: gosec
	res, err = o.UpdateZoneDelegated(zoneRef, ns, "updated by k8gb", false, false, "", uint32(p.config.NSRecordTTL), true, ibcl.EA{})
	m.InfobloxObserveRequestDuration(start, metrics.UpdateZoneDelegated, err == nil)
	return
}

func (p *InfobloxProvider) deleteZoneDelegated(o ibcl.IBObjectManager, fqdn string) error {
	start := time.Now()

	zone, err := o.GetZoneDelegated(fqdn)
	if err != nil {
		return fmt.Errorf("failed to get delegated zone %s: %w", fqdn, err)
	}

	if zone == nil || zone.Ref == "" {
		return fmt.Errorf("delegated zone %s not found or ref is empty", fqdn)
	}

	if _, err := o.DeleteZoneDelegated(zone.Ref); err != nil {
		return err
	}
	m.InfobloxObserveRequestDuration(start, metrics.DeleteZoneDelegated, err == nil)
	return nil
}

func (p *InfobloxProvider) removeGlueAFromDelegatedZone(o ibcl.IBObjectManager, zoneFQDN string, nsName string, ipsToDelete []string) error {

	contains := func(values []string, value string) bool {
		for _, v := range values {
			if v == value {
				return true
			}
		}
		return false
	}

	zone, err := o.GetZoneDelegated(zoneFQDN)
	if err != nil {
		return fmt.Errorf("failed to get delegated zone %s: %w", zoneFQDN, err)
	}

	var filtered []ibcl.NameServer

	for _, ns := range zone.DelegateTo.NameServers {
		if ns.Name == nsName && contains(ipsToDelete, ns.Address) {
			continue
		}
		filtered = append(filtered, ns)
	}

	zone.DelegateTo.NameServers = filtered
	_, err = p.updateZoneDelegated(o, zone.Ref, filtered)
	if err != nil {
		return fmt.Errorf("failed to update delegated zone %s: %w", zoneFQDN, err)
	}
	return nil
}
