---
# debug information for the tests
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: StepTemplate
metadata:
  name: debug
spec:
  try:
    - sleep:
        duration: 30s # reconcile requeue seconds + coreDNS
    - script:
        env:
          - name: NAME
            value: ($test.metadata.name)
        content: |
            GEO_TAG=$(kubectl get deployment k8gb -n k8gb -o json | jq -r '.spec.template.spec.containers[] | select(.name=="k8gb") | .env[] | select(.name=="CLUSTER_GEO_TAG") | .value')
            echo "DEBUG: GEO_TAG = $GEO_TAG"
            
            echo "DBUG: Running pods"
            kubectl -n k8gb get pods 
            
            echo "DEBUG: Running services"
            kubectl -n k8gb get services
          
            echo "DEBUG: DNSEndpoints"
            kubectl -n k8gb get dnsendpoint
