package ipresolver

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"fmt"
	"strings"

	"github.com/k8gb-io/k8gb/controllers/utils"

	"github.com/miekg/dns"
)

// ClusterNSNames map of ns name and tag e.g:
// ["gslb-ns-eu-cloud.example.com": "eu"]
type ClusterNSNames map[string]string

// DiscoverNameServers query extracted parent DNS server for NS records of the loadBalanced zone.
// In this example, zone is cloud.example.com and edge is 172.18.0.6:1053:
//
//	dig @172.18.0.6 -p 1053 cloud.example.com NS +norec
//
// Expected response must contain k8gb NS records in the ANSWER SECTION,
// for example:
//
//	;; ANSWER SECTION:
//	cloud.example.com.        30  IN  NS  gslb-ns-eu-cloud.example.com.
//	cloud.example.com.        30  IN  NS  gslb-ns-us-cloud.example.com.
//
// Geo tags are extracted from NS names matching the k8gb pattern:
//
//	gslb-ns-<geoTag>-<zone>
//
// Examples:
//
//	gslb-ns-eu-cloud.example.com. -> eu
//	gslb-ns-us-cloud.example.com. -> us
//
// Function discovers all nameservers including local and external
func DiscoverNameServers(edge *utils.DNSServer, zone string) (ClusterNSNames, error) {
	const prefix = "gslb-ns-"
	tags := make(map[string]string)

	m := new(dns.Msg)
	m.SetQuestion(zone+".", dns.TypeNS)
	m.RecursionDesired = false // Equivalent to dig +norec

	c := new(dns.Client)
	r, _, err := c.Exchange(m, edge.String())
	if err != nil {
		return tags, err
	}

	if r == nil {
		return tags, fmt.Errorf("empty DNS response for %s via %s", zone, edge.String())
	}

	if r.Rcode != dns.RcodeSuccess {
		return tags, fmt.Errorf("NS query for %s via %s failed with rcode %s", zone, edge.String(), dns.RcodeToString[r.Rcode])
	}

	for _, ans := range r.Answer {
		ns, ok := ans.(*dns.NS)
		if !ok {
			continue
		}

		parts := strings.Split(ns.Ns, prefix)
		if len(parts) != 2 {
			continue
		}

		tag := strings.Split(parts[1], "-")[0]
		clusterNSName := strings.TrimSuffix(ns.Ns, ".")
		tags[clusterNSName] = tag
	}

	return tags, nil
}

// ExtractParentDNSServer query parent DNS server for NS records of parent zone (example.com):
//
//	dig @localhost -p 1053 example.com NS
//
// Expected response must contain NS records for example.com and their glue A records
// in the ADDITIONAL SECTION, for example:
//
//	;; ANSWER SECTION:
//	example.com.              30  IN  NS  gslb-ns-eu.example.com.
//	example.com.              30  IN  NS  gslb-ns-us.example.com.
//
//	;; ADDITIONAL SECTION:
//	gslb-ns-eu.example.com.   30  IN  A   172.18.0.6
//	gslb-ns-us.example.com.   30  IN  A   172.18.0.11
//
// The first A record from the ADDITIONAL SECTION is used as the returned DNS
// server IP. The returned DNSServer keeps the original DNS server port.
//
// Example return value:
//
//	&utils.DNSServer{
//	    Host: "172.18.0.6",
//	    Port: 1053,
//	}
func ExtractParentDNSServer(parentNameServer *utils.DNSServer, parentZone string) (*utils.DNSServer, error) {
	m := new(dns.Msg)
	m.SetQuestion(parentZone+".", dns.TypeNS)

	c := new(dns.Client)
	r, _, err := c.Exchange(m, parentNameServer.String())
	if err != nil {
		return nil, err
	}

	if r == nil {
		return nil, fmt.Errorf("empty DNS response for %s via %s", parentZone, parentNameServer.String())
	}

	if r.Rcode != dns.RcodeSuccess {
		return nil, fmt.Errorf("NS query for %s via %s failed with rcode %s", parentZone, parentNameServer.String(), dns.RcodeToString[r.Rcode])
	}

	for _, ans := range r.Extra {
		a, ok := ans.(*dns.A)
		if !ok {
			continue
		}
		return &utils.DNSServer{Host: a.A.String(), Port: parentNameServer.Port}, nil
	}

	return nil, fmt.Errorf("no A record found in additional section for %s via %s", parentZone, parentNameServer.String())
}
