// Code generated by MockGen. DO NOT EDIT.
// Source: controllers/providers/k8gbendpoint/dnsEndpoint.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=controllers/mocks/endpoint_mock.go -source=controllers/providers/k8gbendpoint/dnsEndpoint.go Assistant
//

// Package mocks is a generated GoMock package.
package mocks

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	endpoint "sigs.k8s.io/external-dns/endpoint"
)

// MockDNSEndpoint is a mock of DNSEndpoint interface.
type MockDNSEndpoint struct {
	ctrl     *gomock.Controller
	recorder *MockDNSEndpointMockRecorder
}

// MockDNSEndpointMockRecorder is the mock recorder for MockDNSEndpoint.
type MockDNSEndpointMockRecorder struct {
	mock *MockDNSEndpoint
}

// NewMockDNSEndpoint creates a new mock instance.
func NewMockDNSEndpoint(ctrl *gomock.Controller) *MockDNSEndpoint {
	mock := &MockDNSEndpoint{ctrl: ctrl}
	mock.recorder = &MockDNSEndpointMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSEndpoint) EXPECT() *MockDNSEndpointMockRecorder {
	return m.recorder
}

// GetDNSEndpoint mocks base method.
func (m *MockDNSEndpoint) GetDNSEndpoint() (*endpoint.DNSEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDNSEndpoint")
	ret0, _ := ret[0].(*endpoint.DNSEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDNSEndpoint indicates an expected call of GetDNSEndpoint.
func (mr *MockDNSEndpointMockRecorder) GetDNSEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDNSEndpoint", reflect.TypeOf((*MockDNSEndpoint)(nil).GetDNSEndpoint))
}

// RemoveEndpoint mocks base method.
func (m *MockDNSEndpoint) RemoveEndpoint() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEndpoint")
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEndpoint indicates an expected call of RemoveEndpoint.
func (mr *MockDNSEndpointMockRecorder) RemoveEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEndpoint", reflect.TypeOf((*MockDNSEndpoint)(nil).RemoveEndpoint))
}

// SaveDNSEndpoint mocks base method.
func (m *MockDNSEndpoint) SaveDNSEndpoint(i *endpoint.DNSEndpoint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDNSEndpoint", i)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDNSEndpoint indicates an expected call of SaveDNSEndpoint.
func (mr *MockDNSEndpointMockRecorder) SaveDNSEndpoint(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDNSEndpoint", reflect.TypeOf((*MockDNSEndpoint)(nil).SaveDNSEndpoint), i)
}
