// Code generated by MockGen. DO NOT EDIT.
// Source: controllers/depresolver/resolver.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=controllers/mocks/resolver_mock.go -source=controllers/depresolver/resolver.go GslbResolver
//

// Package mocks is a generated GoMock package.
package mocks

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	context "context"
	reflect "reflect"

	v1beta1 "github.com/k8gb-io/k8gb/api/v1beta1"
	depresolver "github.com/k8gb-io/k8gb/controllers/depresolver"
	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockGslbResolver is a mock of GslbResolver interface.
type MockGslbResolver struct {
	ctrl     *gomock.Controller
	recorder *MockGslbResolverMockRecorder
}

// MockGslbResolverMockRecorder is the mock recorder for MockGslbResolver.
type MockGslbResolverMockRecorder struct {
	mock *MockGslbResolver
}

// NewMockGslbResolver creates a new mock instance.
func NewMockGslbResolver(ctrl *gomock.Controller) *MockGslbResolver {
	mock := &MockGslbResolver{ctrl: ctrl}
	mock.recorder = &MockGslbResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGslbResolver) EXPECT() *MockGslbResolverMockRecorder {
	return m.recorder
}

// ResolveGslbSpec mocks base method.
func (m *MockGslbResolver) ResolveGslbSpec(ctx context.Context, gslb *v1beta1.Gslb, client client.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveGslbSpec", ctx, gslb, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveGslbSpec indicates an expected call of ResolveGslbSpec.
func (mr *MockGslbResolverMockRecorder) ResolveGslbSpec(ctx, gslb, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveGslbSpec", reflect.TypeOf((*MockGslbResolver)(nil).ResolveGslbSpec), ctx, gslb, client)
}

// ResolveOperatorConfig mocks base method.
func (m *MockGslbResolver) ResolveOperatorConfig() (*depresolver.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveOperatorConfig")
	ret0, _ := ret[0].(*depresolver.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveOperatorConfig indicates an expected call of ResolveOperatorConfig.
func (mr *MockGslbResolverMockRecorder) ResolveOperatorConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveOperatorConfig", reflect.TypeOf((*MockGslbResolver)(nil).ResolveOperatorConfig))
}
