package utils

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"errors"
	"net"

	"github.com/miekg/dns"
)

type DNSQueryResult struct {
	Msg    *dns.Msg
	Status DNSQueryStatus
	Err    error
}

type DNSQueryService interface {
	Query(host string, nameservers DNSList) DNSQueryResult

	ExtractARecords(msg *dns.Msg) []string
}

type DNSQueryServiceImpl struct {
}

func NewDNSQueryService() *DNSQueryServiceImpl {
	return &DNSQueryServiceImpl{}
}

func (i *DNSQueryServiceImpl) Query(host string, nameservers DNSList) DNSQueryResult {
	dnsMsg := new(dns.Msg)
	fqdn := dns.Fqdn(host)
	dnsMsg.SetQuestion(fqdn, dns.TypeA)
	msg, err := Exchange(dnsMsg, nameservers)

	if err != nil {
		if isTimeout(err) {
			return DNSQueryResult{
				Status: DNSQueryStatusTimeout,
				Err:    err,
			}
		}

		return DNSQueryResult{
			Status: DNSQueryStatusError,
			Err:    err,
		}
	}

	switch msg.Rcode {
	case dns.RcodeSuccess:
		records := i.ExtractARecords(msg)
		if len(records) == 0 {
			return DNSQueryResult{
				Msg:    msg,
				Status: DNSQueryStatusNoAnswer,
			}
		}

		return DNSQueryResult{
			Msg:    msg,
			Status: DNSQueryStatusResolved,
		}

	case dns.RcodeServerFailure: // SERVFAIL
		return DNSQueryResult{
			Msg:    msg,
			Status: DNSQueryStatusServerFailure,
		}
	case dns.RcodeRefused: // REFUSED
		return DNSQueryResult{
			Msg:    msg,
			Status: DNSQueryStatusRefused,
		}
	case dns.RcodeNameError:
		return DNSQueryResult{
			Msg:    msg,
			Status: DNSQueryStatusNXDOMAIN,
		}

	default:
		return DNSQueryResult{
			Msg:    msg,
			Status: DNSQueryStatusError,
		}
	}
}

func (i *DNSQueryServiceImpl) ExtractARecords(msg *dns.Msg) []string {
	aRecords := make([]string, 0)
	if msg == nil {
		return aRecords
	}
	for _, answer := range msg.Answer {
		aRecord, ok := answer.(*dns.A)
		if !ok {
			continue
		}
		aRecords = append(aRecords, aRecord.A.String())
	}
	return aRecords
}

func isTimeout(err error) bool {
	var netErr net.Error
	return errors.As(err, &netErr) && netErr.Timeout()
}
