package gatewayapiudproute

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"fmt"

	"github.com/k8gb-io/k8gb/controllers/refresolver/gatewayapi"
	"github.com/k8gb-io/k8gb/controllers/utils"
	gatewayapiv1 "sigs.k8s.io/gateway-api/apis/v1"
	gatewayapiv1alpha2 "sigs.k8s.io/gateway-api/apis/v1alpha2"
)

// UDPRouteAdapter adapts UDPRoute to the gatewayapi.RouteAdapter interface
type UDPRouteAdapter struct {
	udpRoute *gatewayapiv1alpha2.UDPRoute
	hostname string
}

// NewUDPRouteAdapter creates a new UDPRoute adapter
func NewUDPRouteAdapter(udpRoute *gatewayapiv1alpha2.UDPRoute, hostname string) *UDPRouteAdapter {
	return &UDPRouteAdapter{udpRoute: udpRoute, hostname: hostname}
}

func (a *UDPRouteAdapter) GetHostnames() ([]gatewayapiv1.Hostname, error) {
	if a.hostname == "" {
		return nil, fmt.Errorf("UDPRoute %s requires %s annotation", a.udpRoute.Name, utils.HostnameAnnotation)
	}
	return []gatewayapiv1.Hostname{gatewayapiv1.Hostname(a.hostname)}, nil
}

func (a *UDPRouteAdapter) GetParentRefs() []gatewayapiv1.ParentReference {
	return a.udpRoute.Spec.ParentRefs
}

func (a *UDPRouteAdapter) GetRules() []gatewayapi.RouteRule {
	rules := make([]gatewayapi.RouteRule, len(a.udpRoute.Spec.Rules))
	for i := range a.udpRoute.Spec.Rules {
		rules[i] = &UDPRouteRuleAdapter{rule: &a.udpRoute.Spec.Rules[i]}
	}
	return rules
}

func (a *UDPRouteAdapter) GetName() string {
	return a.udpRoute.Name
}

func (a *UDPRouteAdapter) GetNamespace() string {
	return a.udpRoute.Namespace
}

// UDPRouteRuleAdapter adapts UDPRouteRule to the RouteRule interface
type UDPRouteRuleAdapter struct {
	rule *gatewayapiv1alpha2.UDPRouteRule
}

func (a *UDPRouteRuleAdapter) GetBackendRefs() []gatewayapiv1.BackendRef {
	return a.rule.BackendRefs
}
