package gatewayapigrpcroute

/*
Copyright 2021-2025 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"github.com/k8gb-io/k8gb/controllers/refresolver/gatewayapi"
	gatewayapiv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// GRPCRouteAdapter adapts GRPCRoute to the gatewayapi.RouteAdapter interface
type GRPCRouteAdapter struct {
	grpcRoute *gatewayapiv1.GRPCRoute
}

// NewGRPCRouteAdapter creates a new GRPCRoute adapter
func NewGRPCRouteAdapter(grpcRoute *gatewayapiv1.GRPCRoute) *GRPCRouteAdapter {
	return &GRPCRouteAdapter{grpcRoute: grpcRoute}
}

func (a *GRPCRouteAdapter) GetHostnames() ([]gatewayapiv1.Hostname, error) {
	return a.grpcRoute.Spec.Hostnames, nil
}

func (a *GRPCRouteAdapter) GetParentRefs() []gatewayapiv1.ParentReference {
	return a.grpcRoute.Spec.ParentRefs
}

func (a *GRPCRouteAdapter) GetRules() []gatewayapi.RouteRule {
	rules := make([]gatewayapi.RouteRule, len(a.grpcRoute.Spec.Rules))
	for i := range a.grpcRoute.Spec.Rules {
		rules[i] = &GRPCRouteRuleAdapter{rule: &a.grpcRoute.Spec.Rules[i]}
	}
	return rules
}

func (a *GRPCRouteAdapter) GetName() string {
	return a.grpcRoute.Name
}

func (a *GRPCRouteAdapter) GetNamespace() string {
	return a.grpcRoute.Namespace
}

// GRPCRouteRuleAdapter adapts GRPCRouteRule to the RouteRule interface
type GRPCRouteRuleAdapter struct {
	rule *gatewayapiv1.GRPCRouteRule
}

func (a *GRPCRouteRuleAdapter) GetBackendRefs() []gatewayapiv1.BackendRef {
	refs := make([]gatewayapiv1.BackendRef, len(a.rule.BackendRefs))
	for i := range a.rule.BackendRefs {
		refs[i] = a.rule.BackendRefs[i].BackendRef
	}
	return refs
}
