{{- if .Values.k8gb.deployRbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8gb
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "chart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: k8gb
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: k8gb
  apiGroup: rbac.authorization.k8s.io
{{- end }}
