apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: playground-failover
spec:
  resourceRef:
    ingress:
      matchLabels:
        app: playground-failover
  strategy:
    type: failover
    dnsTtlSeconds: 5
    primaryGeoTag: "eu"
