apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: playground-failover-1
spec:
  resourceRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    matchLabels:
      app: playground-failover-1
  strategy:
    type: failover
    dnsTtlSeconds: 5
    primaryGeoTag: "eu"
