apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: playground-failover-2
  namespace: istio-ingress
spec:
  selector:
    app: istio-ingressgateway
  servers:
    - hosts:
        - playground-failover-2.cloud.example.com
      port:
        name: http
        number: 8080
        protocol: http
