name: Helm docs
on:
  push:
    branches:
    - 'master'
    paths:
     - 'chart/k8gb/**'
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build-helm-doc:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    name: Update Helm Doc
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Checkout Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Generate docs for helm chart - chart/k8gb/README.md
      uses: docker://jnorwood/helm-docs@sha256:7e562b49ab6b1dbc50c3da8f2dd6ffa8a5c6bba327b1c6335cc15ce29267979c
      with:
        args: --template-files=_helm-docs-template.gotmpl
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        title: "Update Helm Docs"
        branch: ci-helm-doc
        delete-branch: true
        base: master
        signoff: true
        token: ${{ secrets.GITHUB_TOKEN }}
