name: KubeLinter

on:
  push:
    paths:
      - 'chart/k8gb/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'chart/k8gb/**'
permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Create ../results directory for sarif files
        shell: bash
        run: mkdir -p ../results

      - name: Scan k8gb chart
        id: kube-lint-repo
        uses: stackrox/kube-linter-action@e5759fab01e612c139fe23f264820ba0cf73320c
        with:
          directory: chart/k8gb
          version: 0.2.5
          format: sarif
          output-file: ../results/kube-linter.sarif

      - name: Upload sarif output to GitHub
        uses: github/codeql-action/upload-sarif@c36620d31ac7c881962c3d9dd939c40ec9434f2b # v3.26.12
        continue-on-error: true
